server:
  port: 8084
  
token:
  secret: newTokenSecret

eureka:
  client:
    sevice-url:
      defaultZone: http://172.31.27.127:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: '{cipher}db30d101af0aeee60bcd43f0efe35b651392f383b487ebdb75fa3e8d32288380'
    password: '{cipher}db30d101af0aeee60bcd43f0efe35b651392f383b487ebdb75fa3e8d32288380'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
