spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: '{cipher}db30d101af0aeee60bcd43f0efe35b651392f383b487ebdb75fa3e8d32288380'
    password: '{cipher}db30d101af0aeee60bcd43f0efe35b651392f383b487ebdb75fa3e8d32288380'
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:3306/notes_db
    username: postgres
    password: postgres
resilience4j:
  circuitbreaker:
    instances:
      users-server:
        properties:
          minimumNumberOfCalls: 500
feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    sevice-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application/inctance_id:${random.value}}
    prefer-ip-address: true

server:
  port: ${PORT:8083}