spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: '{cipher}db30d101af0aeee60bcd43f0efe35b651392f383b487ebdb75fa3e8d32288380'
    password: '{cipher}db30d101af0aeee60bcd43f0efe35b651392f383b487ebdb75fa3e8d32288380'
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: '{cipher}5ba7b97b7f9389045bb21c4c1df31ba8681d83abd073c7e0ebb7888507a597c2'
    password: '{cipher}5ba7b97b7f9389045bb21c4c1df31ba8681d83abd073c7e0ebb7888507a597c2'

eureka:
  client:
    sevice-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application/inctance_id:${random.value}}
    prefer-ip-address: true

server:
  port: ${PORT:8082}

token:
  secret: secrettoken

